In [6]:
# Import packages and set numpy random seed
import numpy as np
import cv2
import keras
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Flatten, Dense, Dropout, BatchNormalization
from keras.models import Sequential

#for GPU training
import tensorflow as tf
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())


config = tf.compat.v1.ConfigProto(gpu_options = 
                         tf.compat.v1.GPUOptions(per_process_gpu_memory_fraction=0.33)
# device_count = {'GPU': 1}
)
config.gpu_options.allow_growth = True
session = tf.compat.v1.Session(config=config)
tf.compat.v1.keras.backend.set_session(session)


[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 1511132824322969920
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 3173331764
locality {
  bus_id: 1
  links {
  }
}
incarnation: 18311918145524183777
physical_device_desc: "device: 0, name: NVIDIA GeForce GTX 960M, pci bus id: 0000:02:00.0, compute capability: 5.0"
]


In [13]:


model = Sequential(
[
    keras.Input((128,128,3)),
    Conv2D(32, 5, activation='relu', padding = 'same'),
    BatchNormalization(),
    MaxPooling2D((2,2)),

    Conv2D(32, 5, activation='relu', padding = 'same'),
    BatchNormalization(),
    MaxPooling2D((2,2)),
    Dropout(0.5),

    Conv2D(16, 5, activation='relu', padding = 'same'),
    BatchNormalization(),
    MaxPooling2D((2,2)),

    Conv2D(8, 5, activation='relu', padding = 'same'),
    BatchNormalization(),
    MaxPooling2D((2,2)),
    Dropout(0.5),

    Conv2D(4, 5, activation='relu', padding = 'same'),
    BatchNormalization(),
    MaxPooling2D((2,2)),

    Flatten(),
    Dense(1, activation='sigmoid')
]
)

optimizer = keras.optimizers.Adam(learning_rate=0.01)
loss_fn = keras.losses.BinaryCrossentropy(from_logits=True) #from_logits=True means output probabilities are not normalized
acc_metric = keras.metrics.CategoricalAccuracy()
val_acc_metric = keras.metrics.BinaryAccuracy()

model.summary()
model.load_weights('data_aug_off_model.h5')


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_5 (Conv2D)            (None, 128, 128, 32)      2432      
_________________________________________________________________
batch_normalization_5 (Batch (None, 128, 128, 32)      128       
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 64, 64, 32)        0         
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 64, 64, 32)        25632     
_________________________________________________________________
batch_normalization_6 (Batch (None, 64, 64, 32)        128       
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 32, 32, 32)        0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 32, 32, 32)       

In [14]:
@tf.function
def test_step(x):
    val_preds = model(x, training=False)    
    return val_preds

In [20]:
cap = cv2.VideoCapture(0)

while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()
    frame = cv2.flip(frame,1)

    # Our operations on the frame come here
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    gray=[gray,gray,gray]
    to_test = np.resize(gray,(1,128,128,3))
    print(to_test)
#     print(to_test.shape)
    result = test_step(to_test)
    result = np.reshape(tf.get_static_value(result),(1,1))[0][0]
    
    # Display the resulting frame
    prediction = ''
    if result>0.5:
        prediction = 'non-drowsy'
    else:
        prediction = 'drowsy'
       
    cv2.putText(frame, str(result), (10, 160), cv2.FONT_HERSHEY_PLAIN, 2, (255,255,255), 3) 
    cv2.putText(frame, prediction, (10, 200), cv2.FONT_HERSHEY_PLAIN, 2, (255,255,255), 3) 
    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()

[[[[150 148 139]
   [146 148 145]
   [145 145 145]
   ...
   [177 180 181]
   [180 170 174]
   [179 184 176]]

  [[175 180 180]
   [178 172 176]
   [180 180 182]
   ...
   [164 166 168]
   [166 164 162]
   [156 163 162]]

  [[162 163 162]
   [159 157 159]
   [159 159 162]
   ...
   [181 171 171]
   [174 173 174]
   [178 178 176]]

  ...

  [[151 149 153]
   [150 142 144]
   [134 130 142]
   ...
   [193 186 186]
   [182 184 191]
   [188 188 187]]

  [[185 187 187]
   [187 189 187]
   [187 187 189]
   ...
   [164 161 161]
   [161 163 166]
   [168 168 167]]

  [[170 177 178]
   [178 178 178]
   [178 178 180]
   ...
   [ 67  68  68]
   [ 83  93  92]
   [169 252 252]]]]
[[[[149 147 145]
   [140 145 144]
   [145 128 146]
   ...
   [176 177 180]
   [180 181 179]
   [178 177 178]]

  [[181 181 181]
   [179 179 179]
   [175 176 177]
   ...
   [177 172 171]
   [169 165 163]
   [156 160 162]]

  [[162 159 158]
   [158 161 162]
   [164 164 163]
   ...
   [170 169 171]
   [171 171 171]
   [173 175 

   [173 252 252]]]]
[[[[139 141 142]
   [144 145 144]
   [145 150 154]
   ...
   [178 179 172]
   [171 185 178]
   [178 179 179]]

  [[179 178 176]
   [179 178 176]
   [176 177 177]
   ...
   [167 163 169]
   [165 160 157]
   [162 163 161]]

  [[159 157 158]
   [159 156 155]
   [155 160 153]
   ...
   [183 178 170]
   [169 173 171]
   [170 167 170]]

  ...

  [[135 137 144]
   [141 150 144]
   [137 138 144]
   ...
   [180 186 194]
   [191 191 191]
   [189 186 186]]

  [[186 186 188]
   [186 186 186]
   [184 185 186]
   ...
   [165 166 165]
   [167 168 170]
   [180 172 164]]

  [[168 172 183]
   [191 185 181]
   [180 182 171]
   ...
   [ 70  67  65]
   [ 84  84  89]
   [173 252 252]]]]
[[[[145 154 137]
   [134 149 135]
   [142 144 146]
   ...
   [176 177 178]
   [178 178 174]
   [183 186 179]]

  [[179 180 179]
   [175 174 183]
   [175 174 178]
   ...
   [163 175 166]
   [162 162 160]
   [162 164 162]]

  [[154 157 155]
   [154 161 160]
   [160 161 162]
   ...
   [171 171 171]
   [170 1

[[[[141 140 144]
   [144 140 148]
   [129 142 143]
   ...
   [181 185 175]
   [175 172 173]
   [179 178 179]]

  [[185 184 178]
   [175 177 180]
   [176 173 174]
   ...
   [171 175 170]
   [171 165 166]
   [173 154 159]]

  [[160 159 161]
   [162 162 162]
   [165 168 165]
   ...
   [175 173 171]
   [171 174 179]
   [172 171 168]]

  ...

  [[138 137 148]
   [143 144 144]
   [151 148 144]
   ...
   [187 181 179]
   [185 190 187]
   [186 187 187]]

  [[187 187 186]
   [186 184 187]
   [180 180 183]
   ...
   [164 164 167]
   [167 167 166]
   [166 168 169]]

  [[170 177 178]
   [179 180 182]
   [178 178 176]
   ...
   [ 72  74  69]
   [ 84  86  92]
   [164 253 253]]]]
[[[[141 140 144]
   [144 140 148]
   [129 142 143]
   ...
   [181 185 175]
   [175 172 173]
   [179 178 179]]

  [[185 184 178]
   [175 177 180]
   [176 173 174]
   ...
   [171 175 170]
   [171 165 166]
   [173 154 159]]

  [[160 159 161]
   [162 162 162]
   [165 168 165]
   ...
   [175 173 171]
   [171 174 179]
   [172 171 

[[[[147 148 153]
   [146 141 144]
   [148 152 148]
   ...
   [178 177 169]
   [176 181 179]
   [175 176 174]]

  [[172 180 166]
   [174 179 180]
   [178 176 178]
   ...
   [170 177 170]
   [171 162 160]
   [160 159 158]]

  [[158 160 161]
   [160 162 162]
   [155 159 161]
   ...
   [173 175 172]
   [171 172 171]
   [174 179 169]]

  ...

  [[144 146 147]
   [150 149 145]
   [139 147 154]
   ...
   [187 186 186]
   [187 187 187]
   [187 187 183]]

  [[184 185 181]
   [183 187 189]
   [188 187 182]
   ...
   [165 166 163]
   [164 164 164]
   [165 169 171]]

  [[169 169 173]
   [177 181 179]
   [175 174 176]
   ...
   [ 73  77  75]
   [ 80  91  93]
   [175 251 251]]]]
[[[[147 148 153]
   [146 141 144]
   [148 152 148]
   ...
   [178 177 169]
   [176 181 179]
   [175 176 174]]

  [[172 180 166]
   [174 179 180]
   [178 176 178]
   ...
   [170 177 170]
   [171 162 160]
   [160 159 158]]

  [[158 160 161]
   [160 162 162]
   [155 159 161]
   ...
   [173 175 172]
   [171 172 171]
   [174 179 

[[[[142 133 145]
   [152 149 145]
   [145 145 143]
   ...
   [179 182 180]
   [182 182 174]
   [174 176 175]]

  [[176 180 179]
   [177 178 176]
   [176 175 172]
   ...
   [169 167 166]
   [170 156 155]
   [154 156 157]]

  [[154 157 162]
   [159 155 160]
   [161 160 160]
   ...
   [171 170 171]
   [170 175 176]
   [171 173 171]]

  ...

  [[147 154 154]
   [150 144 161]
   [154 148 149]
   ...
   [184 184 185]
   [186 186 191]
   [184 182 186]]

  [[187 187 187]
   [187 189 190]
   [185 189 190]
   ...
   [165 164 170]
   [174 170 169]
   [168 169 171]]

  [[166 168 179]
   [180 178 182]
   [179 176 177]
   ...
   [ 69  72  75]
   [ 93  95  94]
   [138 253 253]]]]
[[[[138 141 146]
   [145 146 147]
   [148 150 143]
   ...
   [176 176 174]
   [176 178 179]
   [177 174 168]]

  [[173 178 175]
   [171 173 174]
   [176 178 180]
   ...
   [169 164 166]
   [167 167 159]
   [157 156 153]]

  [[163 163 159]
   [155 154 158]
   [163 168 160]
   ...
   [172 172 178]
   [173 168 169]
   [168 170 

[[[[134 145 144]
   [140 144 144]
   [155 136 146]
   ...
   [181 178 174]
   [167 171 176]
   [175 174 171]]

  [[175 179 179]
   [178 174 179]
   [175 177 179]
   ...
   [171 170 170]
   [173 165 154]
   [156 167 166]]

  [[160 157 162]
   [162 160 161]
   [161 162 163]
   ...
   [168 174 171]
   [171 170 169]
   [171 173 176]]

  ...

  [[143 145 152]
   [151 147 146]
   [146 144 149]
   ...
   [184 188 185]
   [184 185 185]
   [184 184 184]]

  [[187 189 189]
   [184 185 185]
   [186 193 187]
   ...
   [165 165 165]
   [165 167 168]
   [168 168 167]]

  [[165 168 177]
   [183 184 178]
   [178 178 176]
   ...
   [ 64  66  71]
   [ 80  81  81]
   [170 252 252]]]]
[[[[139 142 137]
   [138 145 144]
   [143 143 154]
   ...
   [175 177 178]
   [183 175 174]
   [175 174 172]]

  [[173 178 177]
   [176 176 177]
   [179 178 176]
   ...
   [174 177 173]
   [166 163 162]
   [159 160 159]]

  [[161 154 155]
   [160 160 160]
   [154 158 164]
   ...
   [172 168 170]
   [167 171 169]
   [172 175 

[[[[136 138 141]
   [145 146 138]
   [135 139 144]
   ...
   [176 176 178]
   [170 170 180]
   [177 170 179]]

  [[184 184 187]
   [170 176 178]
   [181 170 174]
   ...
   [165 175 169]
   [170 169 168]
   [162 163 163]]

  [[158 156 164]
   [162 163 160]
   [160 162 158]
   ...
   [174 170 170]
   [177 175 173]
   [173 178 176]]

  ...

  [[145 143 148]
   [148 149 152]
   [151 148 144]
   ...
   [185 182 181]
   [186 186 185]
   [185 183 181]]

  [[185 183 186]
   [184 181 184]
   [184 187 187]
   ...
   [162 163 163]
   [167 170 174]
   [177 168 170]]

  [[176 171 186]
   [184 182 177]
   [176 177 175]
   ...
   [ 65  60  68]
   [ 73  81  97]
   [175 252 252]]]]
[[[[136 138 141]
   [145 146 138]
   [135 139 144]
   ...
   [176 176 178]
   [170 170 180]
   [177 170 179]]

  [[184 184 187]
   [170 176 178]
   [181 170 174]
   ...
   [165 175 169]
   [170 169 168]
   [162 163 163]]

  [[158 156 164]
   [162 163 160]
   [160 162 158]
   ...
   [174 170 170]
   [177 175 173]
   [173 178 

[[[[151 137 133]
   [144 151 148]
   [150 151 147]
   ...
   [174 183 177]
   [175 175 176]
   [177 174 165]]

  [[178 180 178]
   [167 179 176]
   [181 183 181]
   ...
   [162 161 161]
   [161 161 152]
   [156 161 161]]

  [[160 159 162]
   [162 161 157]
   [155 155 160]
   ...
   [170 172 162]
   [161 169 169]
   [172 174 171]]

  ...

  [[149 150 150]
   [142 147 147]
   [149 149 147]
   ...
   [186 187 187]
   [187 189 187]
   [184 184 184]]

  [[185 186 187]
   [184 190 192]
   [186 186 184]
   ...
   [158 161 165]
   [165 166 167]
   [169 169 169]]

  [[171 174 179]
   [182 178 178]
   [177 177 175]
   ...
   [ 67  71  67]
   [ 88 102  94]
   [174 252 252]]]]
[[[[130 135 147]
   [144 150 136]
   [137 138 135]
   ...
   [180 178 177]
   [169 177 175]
   [170 174 170]]

  [[173 174 178]
   [179 178 171]
   [166 168 174]
   ...
   [165 161 166]
   [164 164 164]
   [162 154 162]]

  [[161 160 160]
   [160 153 160]
   [164 161 162]
   ...
   [177 171 170]
   [171 173 170]
   [170 171 

[[[[150 154 131]
   [129 150 139]
   [127 144 134]
   ...
   [180 173 177]
   [178 177 171]
   [174 177 177]]

  [[172 165 187]
   [176 167 179]
   [176 167 171]
   ...
   [169 169 174]
   [172 167 161]
   [156 154 158]]

  [[162 162 160]
   [162 163 162]
   [162 162 161]
   ...
   [173 173 177]
   [173 175 156]
   [168 178 171]]

  ...

  [[132 142 147]
   [145 147 151]
   [153 153 153]
   ...
   [184 184 187]
   [188 185 184]
   [187 189 187]]

  [[188 188 186]
   [187 188 186]
   [185 184 184]
   ...
   [167 164 162]
   [162 166 169]
   [173 172 170]]

  [[170 171 175]
   [178 177 178]
   [181 181 182]
   ...
   [ 68  67  61]
   [ 80  95  91]
   [169 252 252]]]]
[[[[138 138 144]
   [133 144 143]
   [144 151 146]
   ...
   [177 179 180]
   [179 178 175]
   [176 180 176]]

  [[172 179 178]
   [177 179 179]
   [179 176 180]
   ...
   [168 170 162]
   [160 163 161]
   [164 161 174]]

  [[159 154 160]
   [160 153 159]
   [162 161 165]
   ...
   [170 169 170]
   [171 174 170]
   [165 171 

[[[[149 141 138]
   [137 134 139]
   [145 146 146]
   ...
   [173 173 175]
   [189 184 177]
   [178 177 167]]

  [[165 177 177]
   [184 167 175]
   [177 173 174]
   ...
   [173 166 162]
   [171 170 162]
   [161 161 160]]

  [[162 162 160]
   [154 169 164]
   [163 164 164]
   ...
   [173 170 162]
   [165 171 171]
   [172 172 169]]

  ...

  [[152 149 144]
   [147 148 143]
   [149 151 149]
   ...
   [182 185 178]
   [178 178 184]
   [186 187 186]]

  [[184 182 183]
   [186 188 186]
   [186 186 184]
   ...
   [161 159 162]
   [167 169 168]
   [168 169 170]]

  [[170 171 178]
   [179 181 178]
   [178 178 175]
   ...
   [ 72  66  65]
   [ 90  83  85]
   [146 253 253]]]]
[[[[144 150 144]
   [140 150 150]
   [145 142 141]
   ...
   [180 179 178]
   [177 175 174]
   [175 174 173]]

  [[182 188 173]
   [170 177 177]
   [179 173 173]
   ...
   [170 169 172]
   [169 166 156]
   [159 160 160]]

  [[159 159 160]
   [157 168 161]
   [152 160 161]
   ...
   [170 170 174]
   [170 169 169]
   [166 171 

[[[[134 138 144]
   [130 144 144]
   [150 135 144]
   ...
   [178 178 177]
   [177 172 176]
   [178 178 174]]

  [[172 176 177]
   [177 175 175]
   [174 173 177]
   ...
   [164 166 171]
   [159 159 161]
   [159 158 158]]

  [[157 158 162]
   [159 158 154]
   [159 160 159]
   ...
   [173 171 171]
   [178 178 172]
   [181 168 164]]

  ...

  [[139 143 144]
   [144 146 148]
   [146 146 147]
   ...
   [180 178 184]
   [183 183 185]
   [185 185 186]]

  [[188 186 186]
   [187 189 191]
   [185 184 185]
   ...
   [167 165 164]
   [161 164 164]
   [167 169 169]]

  [[170 171 174]
   [176 176 183]
   [180 178 174]
   ...
   [ 54  74  79]
   [ 83  89  95]
   [170 253 253]]]]
[[[[134 138 144]
   [130 144 144]
   [150 135 144]
   ...
   [178 178 177]
   [177 172 176]
   [178 178 174]]

  [[172 176 177]
   [177 175 175]
   [174 173 177]
   ...
   [164 166 171]
   [159 159 161]
   [159 158 158]]

  [[157 158 162]
   [159 158 154]
   [159 160 159]
   ...
   [173 171 171]
   [178 178 172]
   [181 168 

[[[[146 146 147]
   [132 145 149]
   [147 138 143]
   ...
   [177 177 174]
   [171 175 178]
   [179 176 174]]

  [[171 173 185]
   [168 172 175]
   [174 174 171]
   ...
   [168 166 169]
   [170 161 162]
   [160 162 170]]

  [[162 159 158]
   [158 157 159]
   [161 160 159]
   ...
   [174 172 166]
   [168 169 170]
   [171 170 168]]

  ...

  [[145 145 149]
   [150 149 149]
   [153 153 148]
   ...
   [184 187 187]
   [184 185 186]
   [187 185 183]]

  [[185 186 184]
   [180 191 188]
   [183 187 189]
   ...
   [164 162 162]
   [167 166 166]
   [168 169 169]]

  [[170 172 178]
   [178 183 184]
   [183 178 176]
   ...
   [ 68  71  81]
   [ 84  81  81]
   [163 253 253]]]]
[[[[146 146 147]
   [132 145 149]
   [147 138 143]
   ...
   [177 177 174]
   [171 175 178]
   [179 176 174]]

  [[171 173 185]
   [168 172 175]
   [174 174 171]
   ...
   [168 166 169]
   [170 161 162]
   [160 162 170]]

  [[162 159 158]
   [158 157 159]
   [161 160 159]
   ...
   [174 172 166]
   [168 169 170]
   [171 170 

[[[[149 144 130]
   [133 140 138]
   [141 139 135]
   ...
   [176 179 178]
   [177 173 177]
   [180 186 180]]

  [[179 177 177]
   [179 180 180]
   [178 180 175]
   ...
   [169 170 170]
   [162 156 160]
   [160 156 160]]

  [[157 160 163]
   [154 154 159]
   [162 162 159]
   ...
   [171 170 170]
   [165 170 174]
   [175 173 171]]

  ...

  [[139 144 138]
   [136 145 144]
   [145 146 152]
   ...
   [187 187 186]
   [186 186 185]
   [185 187 187]]

  [[184 188 189]
   [188 187 186]
   [187 187 187]
   ...
   [166 165 164]
   [164 165 168]
   [166 170 170]]

  [[167 171 179]
   [182 178 177]
   [178 177 172]
   ...
   [ 70  66  84]
   [ 82  85  88]
   [162 254 254]]]]
[[[[143 145 148]
   [136 132 142]
   [145 158 137]
   ...
   [173 175 175]
   [175 177 177]
   [178 179 179]]

  [[179 175 178]
   [176 178 179]
   [179 179 180]
   ...
   [170 166 168]
   [166 161 161]
   [161 159 159]]

  [[160 161 162]
   [162 162 162]
   [161 160 160]
   ...
   [171 166 170]
   [169 171 170]
   [174 179 

[[[[152 152 146]
   [144 151 143]
   [143 142 149]
   ...
   [177 178 178]
   [181 176 171]
   [177 177 175]]

  [[176 177 174]
   [167 176 178]
   [171 172 174]
   ...
   [165 165 167]
   [163 156 162]
   [168 162 157]]

  [[158 166 169]
   [163 160 159]
   [157 158 153]
   ...
   [172 173 170]
   [161 170 176]
   [172 173 171]]

  ...

  [[148 147 144]
   [148 153 150]
   [142 145 150]
   ...
   [185 183 182]
   [186 185 186]
   [185 184 184]]

  [[185 187 187]
   [187 189 190]
   [188 186 187]
   ...
   [161 164 166]
   [168 168 168]
   [169 170 169]]

  [[170 170 175]
   [184 178 178]
   [178 176 172]
   ...
   [ 61  77  70]
   [ 72  89  86]
   [156 252 252]]]]
[[[[152 152 146]
   [144 151 143]
   [143 142 149]
   ...
   [177 178 178]
   [181 176 171]
   [177 177 175]]

  [[176 177 174]
   [167 176 178]
   [171 172 174]
   ...
   [165 165 167]
   [163 156 162]
   [168 162 157]]

  [[158 166 169]
   [163 160 159]
   [157 158 153]
   ...
   [172 173 170]
   [161 170 176]
   [172 173 

[[[[149 146 145]
   [143 140 140]
   [140 129 150]
   ...
   [176 179 184]
   [178 177 178]
   [179 176 176]]

  [[171 182 179]
   [180 175 175]
   [177 176 174]
   ...
   [170 167 171]
   [172 163 162]
   [162 162 160]]

  [[162 162 162]
   [163 163 163]
   [155 158 159]
   ...
   [174 170 170]
   [171 172 174]
   [170 169 170]]

  ...

  [[140 144 147]
   [150 148 145]
   [145 145 145]
   ...
   [185 184 183]
   [184 187 191]
   [189 184 185]]

  [[187 187 185]
   [187 186 188]
   [188 189 189]
   ...
   [157 161 170]
   [162 161 166]
   [169 169 166]]

  [[168 169 176]
   [178 178 180]
   [179 178 173]
   ...
   [ 66  74  71]
   [ 82  90  97]
   [156 253 253]]]]
[[[[149 146 145]
   [143 140 140]
   [140 129 150]
   ...
   [176 179 184]
   [178 177 178]
   [179 176 176]]

  [[171 182 179]
   [180 175 175]
   [177 176 174]
   ...
   [170 167 171]
   [172 163 162]
   [162 162 160]]

  [[162 162 162]
   [163 163 163]
   [155 158 159]
   ...
   [174 170 170]
   [171 172 174]
   [170 169 

[[[[145 146 145]
   [143 143 142]
   [142 145 140]
   ...
   [180 180 179]
   [177 182 175]
   [178 178 178]]

  [[172 171 180]
   [180 174 177]
   [178 168 181]
   ...
   [166 170 168]
   [164 162 161]
   [157 159 161]]

  [[160 159 161]
   [160 158 159]
   [161 161 162]
   ...
   [174 172 164]
   [168 175 173]
   [166 169 174]]

  ...

  [[142 144 147]
   [153 157 150]
   [149 150 148]
   ...
   [191 188 188]
   [189 190 192]
   [190 189 189]]

  [[188 186 186]
   [186 189 189]
   [186 190 183]
   ...
   [170 170 165]
   [164 164 169]
   [170 170 171]]

  [[170 170 176]
   [182 180 180]
   [180 179 177]
   ...
   [ 68  75  74]
   [ 76  81  90]
   [122 241 252]]]]
[[[[141 142 134]
   [131 145 145]
   [138 132 144]
   ...
   [180 178 172]
   [174 173 167]
   [178 179 177]]

  [[174 172 177]
   [178 178 178]
   [181 183 171]
   ...
   [169 168 167]
   [169 167 162]
   [156 158 160]]

  [[164 170 170]
   [167 165 167]
   [167 171 168]
   ...
   [173 171 166]
   [169 174 176]
   [175 175 

[[[[137 137 133]
   [137 138 138]
   [149 138 141]
   ...
   [171 170 171]
   [171 171 170]
   [173 176 169]]

  [[171 172 166]
   [172 166 167]
   [169 173 179]
   ...
   [162 160 168]
   [158 157 157]
   [155 147 153]]

  [[156 154 156]
   [156 155 155]
   [156 158 151]
   ...
   [172 166 163]
   [164 164 164]
   [167 169 165]]

  ...

  [[129 139 146]
   [144 145 143]
   [137 136 137]
   ...
   [180 180 181]
   [182 182 181]
   [179 181 181]]

  [[180 179 180]
   [180 180 180]
   [183 187 183]
   ...
   [161 160 159]
   [165 165 164]
   [164 165 167]]

  [[162 164 164]
   [170 173 174]
   [174 171 165]
   ...
   [ 67  73  68]
   [ 72  77  83]
   [101 211 252]]]]
[[[[142 141 137]
   [142 124 124]
   [135 135 141]
   ...
   [168 172 169]
   [167 164 165]
   [169 162 166]]

  [[168 169 168]
   [164 162 165]
   [166 164 166]
   ...
   [162 164 160]
   [157 155 155]
   [151 153 152]]

  [[153 152 151]
   [151 153 147]
   [142 146 153]
   ...
   [164 163 165]
   [162 162 163]
   [157 164 

[[[[122 126 128]
   [133 129 129]
   [138 135 127]
   ...
   [163 165 165]
   [165 164 163]
   [163 161 162]]

  [[163 163 160]
   [158 162 162]
   [163 163 162]
   ...
   [159 159 156]
   [154 149 140]
   [143 146 151]]

  [[148 145 149]
   [150 152 150]
   [146 146 152]
   ...
   [157 157 155]
   [153 155 160]
   [160 158 156]]

  ...

  [[139 139 131]
   [133 134 136]
   [130 128 133]
   ...
   [172 172 171]
   [171 173 173]
   [174 175 174]]

  [[174 173 172]
   [173 173 173]
   [174 174 174]
   ...
   [154 156 155]
   [154 154 155]
   [155 156 157]]

  [[156 155 162]
   [167 164 168]
   [169 164 163]
   ...
   [ 56  56  56]
   [ 81  81  77]
   [ 89 185 252]]]]
[[[[140 133 129]
   [130 131 138]
   [131 128 129]
   ...
   [163 167 165]
   [151 162 164]
   [163 163 164]]

  [[165 166 165]
   [166 165 165]
   [163 163 162]
   ...
   [157 153 153]
   [161 149 150]
   [148 148 149]]

  [[149 151 148]
   [147 147 147]
   [150 149 153]
   ...
   [160 157 160]
   [158 160 157]
   [159 159 

[[[[116 118 126]
   [125 129 136]
   [123 112 138]
   ...
   [159 161 160]
   [157 156 163]
   [165 161 161]]

  [[162 162 165]
   [158 158 159]
   [158 158 162]
   ...
   [155 152 149]
   [155 151 140]
   [147 148 147]]

  [[148 150 144]
   [147 145 141]
   [145 153 149]
   ...
   [154 153 154]
   [152 153 153]
   [153 154 153]]

  ...

  [[134 134 127]
   [121 138 137]
   [134 135 135]
   ...
   [171 169 167]
   [164 167 168]
   [170 173 170]]

  [[169 168 169]
   [171 171 168]
   [162 171 170]
   ...
   [153 153 151]
   [154 153 154]
   [153 153 151]]

  [[148 153 161]
   [168 164 162]
   [162 162 160]
   ...
   [ 57  65  68]
   [ 66  76  76]
   [122 250 252]]]]
[[[[116 118 126]
   [125 129 136]
   [123 112 138]
   ...
   [159 161 160]
   [157 156 163]
   [165 161 161]]

  [[162 162 165]
   [158 158 159]
   [158 158 162]
   ...
   [155 152 149]
   [155 151 140]
   [147 148 147]]

  [[148 150 144]
   [147 145 141]
   [145 153 149]
   ...
   [154 153 154]
   [152 153 153]
   [153 154 

[[[[134 134 127]
   [127 129 132]
   [138 142 142]
   ...
   [170 167 165]
   [162 162 173]
   [173 163 174]]

  [[169 167 165]
   [164 162 164]
   [163 164 167]
   ...
   [161 159 160]
   [159 154 153]
   [149 151 152]]

  [[152 153 154]
   [154 152 151]
   [151 154 154]
   ...
   [162 162 161]
   [162 162 163]
   [163 163 165]]

  ...

  [[136 136 136]
   [140 141 146]
   [152 147 145]
   ...
   [178 172 172]
   [172 172 175]
   [175 174 174]]

  [[178 179 177]
   [178 178 178]
   [176 177 177]
   ...
   [156 155 153]
   [154 156 158]
   [158 163 162]]

  [[153 157 175]
   [169 168 166]
   [165 165 169]
   ...
   [ 67  67  69]
   [ 80  81  82]
   [166 252 252]]]]
[[[[134 134 127]
   [127 129 132]
   [138 142 142]
   ...
   [170 167 165]
   [162 162 173]
   [173 163 174]]

  [[169 167 165]
   [164 162 164]
   [163 164 167]
   ...
   [161 159 160]
   [159 154 153]
   [149 151 152]]

  [[152 153 154]
   [154 152 151]
   [151 154 154]
   ...
   [162 162 161]
   [162 162 163]
   [163 163 

[[[[140 139 130]
   [137 145 145]
   [143 143 146]
   ...
   [171 173 178]
   [175 176 175]
   [182 178 174]]

  [[180 180 178]
   [170 171 170]
   [170 168 169]
   ...
   [170 167 165]
   [162 155 153]
   [160 156 153]]

  [[157 156 162]
   [162 155 156]
   [163 162 156]
   ...
   [170 170 170]
   [170 171 171]
   [173 168 166]]

  ...

  [[145 146 150]
   [145 144 145]
   [145 144 136]
   ...
   [179 181 182]
   [183 183 184]
   [182 179 180]]

  [[181 182 179]
   [181 187 182]
   [182 188 181]
   ...
   [163 165 169]
   [168 165 165]
   [170 172 167]]

  [[168 170 177]
   [174 182 178]
   [178 178 174]
   ...
   [ 65  70  77]
   [ 90  91  93]
   [180 254 254]]]]
[[[[140 139 130]
   [137 145 145]
   [143 143 146]
   ...
   [171 173 178]
   [175 176 175]
   [182 178 174]]

  [[180 180 178]
   [170 171 170]
   [170 168 169]
   ...
   [170 167 165]
   [162 155 153]
   [160 156 153]]

  [[157 156 162]
   [162 155 156]
   [163 162 156]
   ...
   [170 170 170]
   [170 171 171]
   [173 168 

[[[[138 146 146]
   [139 144 147]
   [136 136 139]
   ...
   [175 168 174]
   [174 182 174]
   [174 174 174]]

  [[178 182 176]
   [174 174 175]
   [172 171 170]
   ...
   [163 169 170]
   [170 165 155]
   [157 155 152]]

  [[156 158 158]
   [154 154 165]
   [163 160 165]
   ...
   [169 170 170]
   [171 172 169]
   [169 170 154]]

  ...

  [[145 146 144]
   [142 144 148]
   [143 140 143]
   ...
   [186 177 179]
   [186 188 186]
   [187 189 188]]

  [[185 184 184]
   [184 184 187]
   [187 184 185]
   ...
   [164 165 166]
   [169 174 173]
   [170 166 166]]

  [[164 165 176]
   [178 178 176]
   [178 175 174]
   ...
   [ 73  72  76]
   [ 86  86  86]
   [172 253 253]]]]
[[[[145 140 140]
   [143 147 137]
   [145 150 128]
   ...
   [178 179 171]
   [183 171 174]
   [177 174 173]]

  [[177 179 177]
   [178 179 179]
   [179 183 184]
   ...
   [165 163 161]
   [159 159 157]
   [154 151 160]]

  [[165 153 164]
   [162 160 162]
   [156 166 155]
   ...
   [170 177 178]
   [171 174 174]
   [171 168 

[[[[128 143 144]
   [143 137 137]
   [140 142 143]
   ...
   [168 176 182]
   [175 174 177]
   [177 177 176]]

  [[174 175 175]
   [175 172 174]
   [178 174 174]
   ...
   [168 167 170]
   [164 149 153]
   [154 154 157]]

  [[159 159 156]
   [156 156 163]
   [159 154 162]
   ...
   [171 170 168]
   [166 170 176]
   [170 169 168]]

  ...

  [[159 158 150]
   [146 145 145]
   [145 149 150]
   ...
   [185 186 186]
   [185 185 184]
   [182 186 188]]

  [[186 186 186]
   [186 186 184]
   [185 185 181]
   ...
   [166 163 163]
   [163 161 169]
   [167 166 166]]

  [[165 161 178]
   [179 178 178]
   [176 173 167]
   ...
   [ 68  73  69]
   [ 77  92  89]
   [170 253 253]]]]
[[[[128 143 144]
   [143 137 137]
   [140 142 143]
   ...
   [168 176 182]
   [175 174 177]
   [177 177 176]]

  [[174 175 175]
   [175 172 174]
   [178 174 174]
   ...
   [168 167 170]
   [164 149 153]
   [154 154 157]]

  [[159 159 156]
   [156 156 163]
   [159 154 162]
   ...
   [171 170 168]
   [166 170 176]
   [170 169 

[[[[150 143 136]
   [125 140 145]
   [138 138 146]
   ...
   [175 175 172]
   [174 176 175]
   [174 174 172]]

  [[172 178 176]
   [175 171 175]
   [179 173 180]
   ...
   [162 165 161]
   [163 153 160]
   [162 156 160]]

  [[161 160 157]
   [156 159 155]
   [155 155 160]
   ...
   [170 170 170]
   [169 170 173]
   [173 171 170]]

  ...

  [[149 149 151]
   [144 144 144]
   [143 143 149]
   ...
   [183 184 187]
   [187 185 184]
   [184 183 182]]

  [[179 182 183]
   [183 185 185]
   [183 187 187]
   ...
   [159 171 163]
   [162 163 162]
   [166 170 168]]

  [[167 163 173]
   [182 178 177]
   [176 175 168]
   ...
   [ 68  75  73]
   [ 81  98  89]
   [180 252 252]]]]
[[[[150 143 136]
   [125 140 145]
   [138 138 146]
   ...
   [175 175 172]
   [174 176 175]
   [174 174 172]]

  [[172 178 176]
   [175 171 175]
   [179 173 180]
   ...
   [162 165 161]
   [163 153 160]
   [162 156 160]]

  [[161 160 157]
   [156 159 155]
   [155 155 160]
   ...
   [170 170 170]
   [169 170 173]
   [173 171 

[[[[132 139 137]
   [137 144 142]
   [139 138 142]
   ...
   [172 170 169]
   [169 169 171]
   [174 176 175]]

  [[179 179 170]
   [163 164 171]
   [173 160 172]
   ...
   [175 170 168]
   [162 162 154]
   [159 154 154]]

  [[157 158 160]
   [162 158 153]
   [155 159 158]
   ...
   [167 168 171]
   [168 169 170]
   [170 167 169]]

  ...

  [[150 152 144]
   [131 148 154]
   [143 140 146]
   ...
   [182 184 183]
   [186 186 186]
   [183 186 187]]

  [[188 188 187]
   [188 186 184]
   [186 186 182]
   ...
   [164 163 163]
   [164 166 166]
   [166 167 167]]

  [[168 169 171]
   [176 178 178]
   [175 175 175]
   ...
   [ 67  66  62]
   [ 76  95  87]
   [155 253 253]]]]
[[[[132 139 137]
   [137 144 142]
   [139 138 142]
   ...
   [172 170 169]
   [169 169 171]
   [174 176 175]]

  [[179 179 170]
   [163 164 171]
   [173 160 172]
   ...
   [175 170 168]
   [162 162 154]
   [159 154 154]]

  [[157 158 160]
   [162 158 153]
   [155 159 158]
   ...
   [167 168 171]
   [168 169 170]
   [170 167 

[[[[139 140 131]
   [141 143 128]
   [136 139 142]
   ...
   [171 175 176]
   [172 165 172]
   [177 176 175]]

  [[168 168 181]
   [178 171 178]
   [170 170 174]
   ...
   [165 160 162]
   [161 158 163]
   [161 146 153]]

  [[162 156 157]
   [156 160 163]
   [154 159 157]
   ...
   [170 169 171]
   [172 173 169]
   [172 179 173]]

  ...

  [[148 156 149]
   [145 145 141]
   [142 147 147]
   ...
   [179 180 187]
   [182 182 184]
   [180 180 184]]

  [[183 184 185]
   [177 186 192]
   [185 188 186]
   ...
   [164 164 164]
   [162 161 163]
   [167 168 169]]

  [[165 166 172]
   [176 175 177]
   [175 173 170]
   ...
   [ 67  73  73]
   [ 73  80  90]
   [171 253 253]]]]
[[[[139 149 137]
   [128 138 139]
   [143 156 148]
   ...
   [174 174 173]
   [171 168 170]
   [174 171 173]]

  [[174 175 176]
   [177 176 175]
   [175 172 180]
   ...
   [161 167 168]
   [163 159 157]
   [157 157 158]]

  [[161 157 152]
   [155 155 157]
   [155 156 159]
   ...
   [167 167 162]
   [162 170 178]
   [174 171 

[[[[146 144 142]
   [141 141 142]
   [141 140 138]
   ...
   [169 170 178]
   [175 182 174]
   [172 177 173]]

  [[177 177 178]
   [176 171 171]
   [173 172 167]
   ...
   [163 163 172]
   [162 161 159]
   [158 153 153]]

  [[153 151 157]
   [156 155 160]
   [159 158 154]
   ...
   [170 167 170]
   [170 170 167]
   [168 176 177]]

  ...

  [[146 147 148]
   [146 144 144]
   [140 140 144]
   ...
   [179 182 187]
   [186 184 184]
   [187 186 187]]

  [[186 185 186]
   [186 183 184]
   [185 185 187]
   ...
   [164 168 163]
   [170 163 168]
   [169 165 165]]

  [[162 167 175]
   [171 178 181]
   [178 181 173]
   ...
   [ 61  72  73]
   [ 79  81  80]
   [165 252 252]]]]
[[[[146 144 142]
   [141 141 142]
   [141 140 138]
   ...
   [169 170 178]
   [175 182 174]
   [172 177 173]]

  [[177 177 178]
   [176 171 171]
   [173 172 167]
   ...
   [163 163 172]
   [162 161 159]
   [158 153 153]]

  [[153 151 157]
   [156 155 160]
   [159 158 154]
   ...
   [170 167 170]
   [170 170 167]
   [168 176 

[[[[144 143 142]
   [146 141 140]
   [141 141 144]
   ...
   [176 177 174]
   [171 171 175]
   [175 175 167]]

  [[171 176 178]
   [175 174 174]
   [176 169 171]
   ...
   [169 166 171]
   [165 162 160]
   [156 156 157]]

  [[159 160 162]
   [158 155 158]
   [158 162 159]
   ...
   [172 171 168]
   [167 173 171]
   [165 176 173]]

  ...

  [[147 146 143]
   [145 147 148]
   [147 147 150]
   ...
   [183 183 188]
   [187 182 178]
   [182 183 180]]

  [[182 184 182]
   [181 184 184]
   [181 178 184]
   ...
   [166 163 161]
   [160 162 164]
   [162 167 169]]

  [[169 170 173]
   [173 177 187]
   [178 171 171]
   ...
   [ 63  70  67]
   [ 72  87  89]
   [160 251 251]]]]
[[[[144 143 142]
   [146 141 140]
   [141 141 144]
   ...
   [176 177 174]
   [171 171 175]
   [175 175 167]]

  [[171 176 178]
   [175 174 174]
   [176 169 171]
   ...
   [169 166 171]
   [165 162 160]
   [156 156 157]]

  [[159 160 162]
   [158 155 158]
   [158 162 159]
   ...
   [172 171 168]
   [167 173 171]
   [165 176 

[[[[145 145 136]
   [136 135 135]
   [137 140 145]
   ...
   [176 178 175]
   [176 178 178]
   [171 170 170]]

  [[171 174 174]
   [174 175 174]
   [171 166 174]
   ...
   [169 170 170]
   [164 158 154]
   [155 156 156]]

  [[157 157 158]
   [158 156 153]
   [160 162 159]
   ...
   [171 171 171]
   [171 172 171]
   [170 168 176]]

  ...

  [[150 149 140]
   [143 147 147]
   [143 144 143]
   ...
   [183 181 181]
   [183 188 186]
   [186 182 181]]

  [[181 185 183]
   [179 182 185]
   [186 185 184]
   ...
   [163 163 164]
   [163 165 163]
   [161 162 166]]

  [[163 165 178]
   [178 179 181]
   [171 170 170]
   ...
   [ 75  77  71]
   [ 81  93  94]
   [165 253 253]]]]
[[[[147 144 145]
   [146 155 143]
   [130 151 153]
   ...
   [176 180 180]
   [171 171 176]
   [181 176 176]]

  [[175 175 174]
   [173 175 178]
   [178 164 171]
   ...
   [166 168 169]
   [166 162 159]
   [158 157 158]]

  [[160 161 162]
   [162 158 158]
   [161 161 157]
   ...
   [175 170 169]
   [164 169 170]
   [170 167 

[[[[138 131 137]
   [139 142 143]
   [142 138 138]
   ...
   [171 174 178]
   [170 170 173]
   [176 165 176]]

  [[177 180 178]
   [176 174 176]
   [174 170 177]
   ...
   [161 164 166]
   [162 162 155]
   [154 156 154]]

  [[156 155 161]
   [159 158 159]
   [162 164 159]
   ...
   [167 170 173]
   [171 171 172]
   [175 171 164]]

  ...

  [[137 145 143]
   [139 146 151]
   [149 146 145]
   ...
   [184 183 181]
   [176 176 181]
   [184 182 184]]

  [[183 182 180]
   [183 184 183]
   [183 183 181]
   ...
   [167 162 161]
   [165 167 168]
   [170 168 167]]

  [[165 166 178]
   [187 178 184]
   [174 171 173]
   ...
   [ 65  66  73]
   [ 84  82  92]
   [178 252 252]]]]
[[[[145 137 140]
   [143 136 134]
   [134 133 132]
   ...
   [175 179 177]
   [178 178 177]
   [183 173 174]]

  [[176 174 177]
   [178 177 176]
   [175 161 170]
   ...
   [167 165 163]
   [158 156 161]
   [162 158 155]]

  [[158 159 160]
   [158 160 161]
   [156 162 160]
   ...
   [162 164 171]
   [168 170 170]
   [170 170 

[[[[144 141 142]
   [144 142 140]
   [141 142 142]
   ...
   [174 179 170]
   [171 175 175]
   [177 172 171]]

  [[173 173 174]
   [174 166 170]
   [177 174 169]
   ...
   [166 163 167]
   [162 153 153]
   [153 157 159]]

  [[156 155 157]
   [158 157 159]
   [158 158 159]
   ...
   [171 170 171]
   [171 165 164]
   [165 165 170]]

  ...

  [[146 147 147]
   [147 154 155]
   [147 143 153]
   ...
   [183 186 185]
   [184 183 183]
   [183 181 181]]

  [[181 182 183]
   [184 187 188]
   [188 185 181]
   ...
   [158 162 162]
   [162 164 164]
   [164 166 169]]

  [[173 167 175]
   [179 177 178]
   [174 172 172]
   ...
   [ 67  72  68]
   [ 70  73  87]
   [164 253 253]]]]
[[[[144 141 142]
   [144 142 140]
   [141 142 142]
   ...
   [174 179 170]
   [171 175 175]
   [177 172 171]]

  [[173 173 174]
   [174 166 170]
   [177 174 169]
   ...
   [166 163 167]
   [162 153 153]
   [153 157 159]]

  [[156 155 157]
   [158 157 159]
   [158 158 159]
   ...
   [171 170 171]
   [171 165 164]
   [165 165 

[[[[148 147 139]
   [138 153 150]
   [138 133 144]
   ...
   [175 175 177]
   [179 170 171]
   [177 169 171]]

  [[175 175 177]
   [177 173 171]
   [170 167 177]
   ...
   [169 173 169]
   [165 163 162]
   [159 158 159]]

  [[161 160 160]
   [158 157 159]
   [160 160 158]
   ...
   [174 169 165]
   [169 170 164]
   [165 169 168]]

  ...

  [[145 149 149]
   [148 147 147]
   [147 143 140]
   ...
   [185 185 183]
   [185 183 186]
   [182 181 183]]

  [[184 184 184]
   [184 183 183]
   [183 183 183]
   ...
   [165 162 162]
   [167 167 166]
   [165 167 166]]

  [[162 169 175]
   [176 177 177]
   [178 176 172]
   ...
   [ 69  73  74]
   [ 76  90  93]
   [171 252 252]]]]
[[[[148 147 139]
   [138 153 150]
   [138 133 144]
   ...
   [175 175 177]
   [179 170 171]
   [177 169 171]]

  [[175 175 177]
   [177 173 171]
   [170 167 177]
   ...
   [169 173 169]
   [165 163 162]
   [159 158 159]]

  [[161 160 160]
   [158 157 159]
   [160 160 158]
   ...
   [174 169 165]
   [169 170 164]
   [165 169 

[[[[129 142 144]
   [139 136 130]
   [140 137 140]
   ...
   [177 174 171]
   [170 170 165]
   [182 177 165]]

  [[171 174 172]
   [170 172 172]
   [175 174 171]
   ...
   [166 168 166]
   [167 169 158]
   [154 159 154]]

  [[157 160 159]
   [157 162 167]
   [153 151 159]
   ...
   [169 169 171]
   [169 170 170]
   [169 169 171]]

  ...

  [[144 144 152]
   [149 143 142]
   [141 144 149]
   ...
   [183 183 183]
   [185 186 187]
   [187 185 186]]

  [[187 185 186]
   [186 190 185]
   [186 185 183]
   ...
   [158 163 165]
   [161 166 167]
   [170 169 166]]

  [[164 166 179]
   [185 181 177]
   [183 174 169]
   ...
   [ 70  70  70]
   [ 83  83  86]
   [168 251 251]]]]
[[[[129 142 144]
   [139 136 130]
   [140 137 140]
   ...
   [177 174 171]
   [170 170 165]
   [182 177 165]]

  [[171 174 172]
   [170 172 172]
   [175 174 171]
   ...
   [166 168 166]
   [167 169 158]
   [154 159 154]]

  [[157 160 159]
   [157 162 167]
   [153 151 159]
   ...
   [169 169 171]
   [169 170 170]
   [169 169 

[[[[147 154 149]
   [147 143 143]
   [143 140 139]
   ...
   [173 171 173]
   [167 169 177]
   [173 172 173]]

  [[173 184 178]
   [180 179 174]
   [174 175 175]
   ...
   [177 174 165]
   [162 157 158]
   [156 158 162]]

  [[155 154 161]
   [166 156 153]
   [159 159 157]
   ...
   [167 167 170]
   [169 170 171]
   [171 169 166]]

  ...

  [[144 148 148]
   [150 149 145]
   [146 149 147]
   ...
   [185 185 187]
   [187 183 182]
   [182 185 188]]

  [[182 181 183]
   [185 185 182]
   [181 184 183]
   ...
   [162 165 167]
   [165 167 167]
   [169 168 168]]

  [[166 164 178]
   [185 177 175]
   [176 172 173]
   ...
   [ 67  66  70]
   [ 86  85  97]
   [158 252 252]]]]
[[[[147 154 149]
   [147 143 143]
   [143 140 139]
   ...
   [173 171 173]
   [167 169 177]
   [173 172 173]]

  [[173 184 178]
   [180 179 174]
   [174 175 175]
   ...
   [177 174 165]
   [162 157 158]
   [156 158 162]]

  [[155 154 161]
   [166 156 153]
   [159 159 157]
   ...
   [167 167 170]
   [169 170 171]
   [171 169 

[[[[138 138 146]
   [147 142 139]
   [137 133 137]
   ...
   [176 176 173]
   [170 171 182]
   [179 173 167]]

  [[170 172 170]
   [170 171 174]
   [170 167 172]
   ...
   [169 163 164]
   [162 153 152]
   [160 157 158]]

  [[165 159 155]
   [162 157 155]
   [159 160 153]
   ...
   [178 168 168]
   [171 171 167]
   [161 166 170]]

  ...

  [[157 150 145]
   [145 147 150]
   [145 149 148]
   ...
   [184 185 185]
   [182 179 182]
   [183 183 185]]

  [[188 186 187]
   [178 181 183]
   [182 181 184]
   ...
   [160 158 162]
   [162 161 161]
   [163 161 167]]

  [[170 172 174]
   [176 179 180]
   [178 178 173]
   ...
   [ 70  73  66]
   [ 75  76  78]
   [168 251 251]]]]
[[[[143 143 143]
   [129 146 155]
   [137 137 136]
   ...
   [179 178 176]
   [176 177 177]
   [177 177 178]]

  [[175 172 171]
   [171 174 177]
   [177 173 175]
   ...
   [166 165 162]
   [165 161 157]
   [158 157 156]]

  [[158 161 168]
   [162 158 156]
   [154 163 159]
   ...
   [173 171 171]
   [174 176 174]
   [167 167 

[[[[147 149 140]
   [134 143 142]
   [139 138 153]
   ...
   [183 170 170]
   [174 175 179]
   [183 178 173]]

  [[177 180 177]
   [173 173 176]
   [178 170 176]
   ...
   [168 167 168]
   [168 162 157]
   [157 157 157]]

  [[158 156 154]
   [156 154 155]
   [158 153 156]
   ...
   [171 171 170]
   [170 170 168]
   [169 171 170]]

  ...

  [[147 147 147]
   [147 146 145]
   [143 145 145]
   ...
   [180 182 180]
   [182 183 185]
   [185 185 181]]

  [[184 184 184]
   [183 182 183]
   [183 184 181]
   ...
   [160 158 160]
   [162 162 166]
   [163 161 162]]

  [[165 167 174]
   [178 176 173]
   [170 173 178]
   ...
   [ 62  63  72]
   [ 82  83  87]
   [141 252 252]]]]
[[[[145 142 140]
   [140 137 150]
   [144 144 144]
   ...
   [171 178 176]
   [176 177 177]
   [176 171 165]]

  [[165 172 175]
   [173 166 170]
   [175 174 168]
   ...
   [171 171 162]
   [157 160 162]
   [162 159 156]]

  [[154 153 157]
   [154 150 156]
   [163 163 157]
   ...
   [170 169 170]
   [171 171 177]
   [174 174 

[[[[136 146 145]
   [145 140 134]
   [135 138 135]
   ...
   [175 172 174]
   [178 184 173]
   [171 171 171]]

  [[169 174 177]
   [176 176 173]
   [173 170 170]
   ...
   [169 170 162]
   [159 154 156]
   [156 157 158]]

  [[162 162 160]
   [155 154 162]
   [160 161 160]
   ...
   [170 172 168]
   [162 168 169]
   [171 171 171]]

  ...

  [[137 146 148]
   [148 146 142]
   [140 135 140]
   ...
   [186 187 181]
   [181 182 181]
   [189 186 179]]

  [[184 181 182]
   [182 185 185]
   [184 185 183]
   ...
   [165 163 162]
   [166 167 163]
   [166 170 168]]

  [[165 169 176]
   [182 178 176]
   [174 170 173]
   ...
   [ 64  77  73]
   [ 82  91  88]
   [168 252 252]]]]
[[[[143 146 141]
   [148 145 140]
   [135 135 142]
   ...
   [170 175 175]
   [176 175 159]
   [169 184 176]]

  [[176 173 179]
   [183 171 171]
   [171 172 175]
   ...
   [168 169 170]
   [165 162 157]
   [158 160 158]]

  [[158 157 149]
   [154 159 159]
   [158 153 155]
   ...
   [172 173 170]
   [168 169 171]
   [169 170 

[[[[150 150 146]
   [146 146 153]
   [139 141 153]
   ...
   [174 174 174]
   [175 177 175]
   [173 173 171]]

  [[171 172 173]
   [175 176 174]
   [172 170 167]
   ...
   [168 167 169]
   [159 156 159]
   [160 154 154]]

  [[157 159 162]
   [165 162 165]
   [162 162 166]
   ...
   [168 177 173]
   [170 175 171]
   [170 170 171]]

  ...

  [[147 152 150]
   [146 146 147]
   [144 136 141]
   ...
   [182 183 184]
   [187 176 182]
   [184 185 184]]

  [[183 185 187]
   [185 187 185]
   [185 184 183]
   ...
   [165 163 156]
   [158 165 174]
   [172 169 167]]

  [[166 168 176]
   [181 181 178]
   [178 175 173]
   ...
   [ 58  74  77]
   [ 80  83  89]
   [178 253 253]]]]
[[[[150 150 146]
   [146 146 153]
   [139 141 153]
   ...
   [174 174 174]
   [175 177 175]
   [173 173 171]]

  [[171 172 173]
   [175 176 174]
   [172 170 167]
   ...
   [168 167 169]
   [159 156 159]
   [160 154 154]]

  [[157 159 162]
   [165 162 165]
   [162 162 166]
   ...
   [168 177 173]
   [170 175 171]
   [170 170 

[[[[134 138 137]
   [136 144 140]
   [136 139 137]
   ...
   [176 176 171]
   [165 168 178]
   [174 170 173]]

  [[176 178 175]
   [173 173 172]
   [172 171 170]
   ...
   [168 168 166]
   [163 159 159]
   [158 157 155]]

  [[156 159 154]
   [163 159 158]
   [157 156 154]
   ...
   [170 169 167]
   [166 169 165]
   [176 172 169]]

  ...

  [[141 142 143]
   [146 149 142]
   [146 146 137]
   ...
   [181 182 182]
   [182 182 181]
   [179 178 179]]

  [[183 183 181]
   [181 184 185]
   [184 184 181]
   ...
   [164 163 163]
   [167 167 170]
   [172 172 170]]

  [[169 170 171]
   [176 177 176]
   [170 171 171]
   ...
   [ 63  65  65]
   [ 73 100  94]
   [181 254 254]]]]
[[[[154 142 145]
   [143 139 139]
   [140 135 133]
   ...
   [171 178 177]
   [177 176 171]
   [181 176 174]]

  [[173 171 175]
   [172 172 172]
   [178 171 172]
   ...
   [168 161 162]
   [161 158 153]
   [156 160 159]]

  [[159 158 158]
   [159 159 156]
   [156 159 156]
   ...
   [172 170 170]
   [171 171 171]
   [169 166 

[[[[129 133 140]
   [143 142 131]
   [126 142 152]
   ...
   [177 178 174]
   [174 175 174]
   [169 173 171]]

  [[176 171 174]
   [175 174 171]
   [174 178 176]
   ...
   [171 171 168]
   [159 160 160]
   [156 152 158]]

  [[151 153 158]
   [158 161 165]
   [160 161 162]
   ...
   [165 165 170]
   [170 166 169]
   [170 170 170]]

  ...

  [[141 147 148]
   [149 146 147]
   [149 146 146]
   ...
   [184 185 185]
   [184 184 182]
   [182 181 182]]

  [[183 184 184]
   [184 184 183]
   [185 187 184]
   ...
   [165 170 167]
   [163 161 162]
   [163 162 167]]

  [[168 170 173]
   [176 174 174]
   [177 177 176]
   ...
   [ 67  74  78]
   [ 78  77  87]
   [132 253 253]]]]
[[[[129 133 140]
   [143 142 131]
   [126 142 152]
   ...
   [177 178 174]
   [174 175 174]
   [169 173 171]]

  [[176 171 174]
   [175 174 171]
   [174 178 176]
   ...
   [171 171 168]
   [159 160 160]
   [156 152 158]]

  [[151 153 158]
   [158 161 165]
   [160 161 162]
   ...
   [165 165 170]
   [170 166 169]
   [170 170 

[[[[140 134 135]
   [134 137 145]
   [142 143 146]
   ...
   [180 176 174]
   [171 175 174]
   [178 177 173]]

  [[177 175 170]
   [164 167 175]
   [178 170 173]
   ...
   [166 171 169]
   [164 159 160]
   [158 148 162]]

  [[162 163 160]
   [160 154 158]
   [156 158 161]
   ...
   [172 177 173]
   [171 170 170]
   [172 170 162]]

  ...

  [[146 145 141]
   [143 142 138]
   [140 144 144]
   ...
   [183 184 186]
   [184 183 184]
   [184 182 181]]

  [[181 182 181]
   [180 183 184]
   [185 184 185]
   ...
   [162 164 162]
   [162 168 169]
   [167 164 166]]

  [[166 162 178]
   [186 177 178]
   [183 178 174]
   ...
   [ 66  68  76]
   [ 80  91  85]
   [139 254 254]]]]
[[[[140 134 135]
   [134 137 145]
   [142 143 146]
   ...
   [180 176 174]
   [171 175 174]
   [178 177 173]]

  [[177 175 170]
   [164 167 175]
   [178 170 173]
   ...
   [166 171 169]
   [164 159 160]
   [158 148 162]]

  [[162 163 160]
   [160 154 158]
   [156 158 161]
   ...
   [172 177 173]
   [171 170 170]
   [172 170 

[[[[144 145 136]
   [130 138 146]
   [134 144 146]
   ...
   [171 177 165]
   [166 175 168]
   [171 173 171]]

  [[174 179 171]
   [165 173 176]
   [175 171 171]
   ...
   [165 162 162]
   [163 159 159]
   [158 158 159]]

  [[159 158 159]
   [161 161 158]
   [157 157 159]
   ...
   [176 171 171]
   [165 166 170]
   [169 170 170]]

  ...

  [[139 142 149]
   [149 145 144]
   [146 147 141]
   ...
   [184 181 180]
   [179 179 179]
   [181 185 182]]

  [[178 180 186]
   [186 185 185]
   [182 182 185]
   ...
   [165 169 166]
   [160 155 162]
   [166 167 168]]

  [[170 172 178]
   [178 179 177]
   [170 173 174]
   ...
   [ 69  71  71]
   [ 85  91  90]
   [154 252 252]]]]
[[[[144 145 136]
   [130 138 146]
   [134 144 146]
   ...
   [171 177 165]
   [166 175 168]
   [171 173 171]]

  [[174 179 171]
   [165 173 176]
   [175 171 171]
   ...
   [165 162 162]
   [163 159 159]
   [158 158 159]]

  [[159 158 159]
   [161 161 158]
   [157 157 159]
   ...
   [176 171 171]
   [165 166 170]
   [169 170 

[[[[139 142 144]
   [142 136 147]
   [153 145 150]
   ...
   [178 175 175]
   [176 174 173]
   [172 173 174]]

  [[174 176 182]
   [176 173 174]
   [173 173 174]
   ...
   [170 167 166]
   [161 158 158]
   [154 154 153]]

  [[155 155 159]
   [160 153 153]
   [159 162 162]
   ...
   [169 171 169]
   [162 170 170]
   [169 163 165]]

  ...

  [[143 145 147]
   [150 144 145]
   [146 148 150]
   ...
   [184 182 182]
   [183 183 183]
   [183 182 178]]

  [[177 182 185]
   [185 183 178]
   [180 179 178]
   ...
   [157 162 165]
   [165 166 166]
   [167 167 164]]

  [[166 170 170]
   [179 178 178]
   [176 172 176]
   ...
   [ 68  81  77]
   [ 82  77  88]
   [147 254 254]]]]
[[[[131 138 144]
   [137 149 153]
   [149 152 143]
   ...
   [171 170 170]
   [169 171 175]
   [174 174 174]]

  [[176 178 176]
   [175 171 171]
   [173 172 175]
   ...
   [167 170 171]
   [163 156 158]
   [159 160 162]]

  [[156 155 163]
   [155 156 156]
   [151 162 161]
   ...
   [171 168 168]
   [169 172 173]
   [176 171 

[[[[135 143 136]
   [136 141 144]
   [145 139 144]
   ...
   [171 176 174]
   [171 171 170]
   [174 171 172]]

  [[170 173 163]
   [159 166 171]
   [172 171 172]
   ...
   [164 167 168]
   [167 156 154]
   [149 158 158]]

  [[158 161 159]
   [148 151 153]
   [158 158 158]
   ...
   [165 166 166]
   [164 167 171]
   [170 168 171]]

  ...

  [[151 144 147]
   [145 141 145]
   [146 148 148]
   ...
   [183 182 183]
   [184 182 183]
   [182 180 182]]

  [[185 184 179]
   [180 185 185]
   [186 184 184]
   ...
   [161 163 164]
   [165 164 163]
   [164 165 166]]

  [[166 172 177]
   [181 177 177]
   [177 171 172]
   ...
   [ 62  70  68]
   [ 70  84  86]
   [162 253 253]]]]
[[[[135 143 136]
   [136 141 144]
   [145 139 144]
   ...
   [171 176 174]
   [171 171 170]
   [174 171 172]]

  [[170 173 163]
   [159 166 171]
   [172 171 172]
   ...
   [164 167 168]
   [167 156 154]
   [149 158 158]]

  [[158 161 159]
   [148 151 153]
   [158 158 158]
   ...
   [165 166 166]
   [164 167 171]
   [170 168 

[[[[157 148 144]
   [145 147 156]
   [129 145 153]
   ...
   [170 175 176]
   [175 176 177]
   [177 172 171]]

  [[177 179 178]
   [174 170 171]
   [173 172 174]
   ...
   [163 168 168]
   [170 159 156]
   [159 158 163]]

  [[162 154 153]
   [154 154 154]
   [158 159 161]
   ...
   [170 167 163]
   [170 170 170]
   [170 170 169]]

  ...

  [[148 145 145]
   [144 143 144]
   [147 147 145]
   ...
   [183 182 180]
   [181 182 182]
   [183 186 190]]

  [[184 184 184]
   [182 187 178]
   [186 190 181]
   ...
   [164 162 160]
   [158 162 166]
   [167 167 165]]

  [[162 159 170]
   [178 177 179]
   [183 182 174]
   ...
   [ 68  67  64]
   [ 81  73  89]
   [162 252 252]]]]
[[[[157 148 144]
   [145 147 156]
   [129 145 153]
   ...
   [170 175 176]
   [175 176 177]
   [177 172 171]]

  [[177 179 178]
   [174 170 171]
   [173 172 174]
   ...
   [163 168 168]
   [170 159 156]
   [159 158 163]]

  [[162 154 153]
   [154 154 154]
   [158 159 161]
   ...
   [170 167 163]
   [170 170 170]
   [170 170 

[[[[143 136 142]
   [145 140 139]
   [136 139 142]
   ...
   [179 175 171]
   [177 175 172]
   [172 175 175]]

  [[176 178 171]
   [169 170 179]
   [174 174 174]
   ...
   [172 169 165]
   [159 159 154]
   [153 153 154]]

  [[158 157 154]
   [164 156 152]
   [154 155 159]
   ...
   [174 168 170]
   [169 167 167]
   [170 173 170]]

  ...

  [[149 146 142]
   [137 143 145]
   [142 145 148]
   ...
   [181 182 181]
   [181 179 181]
   [179 179 185]]

  [[183 184 181]
   [181 182 183]
   [185 178 179]
   ...
   [163 165 165]
   [163 164 165]
   [167 167 162]]

  [[158 170 175]
   [175 175 182]
   [177 175 174]
   ...
   [ 67  71  73]
   [ 85  81  80]
   [167 253 253]]]]
[[[[143 136 142]
   [145 140 139]
   [136 139 142]
   ...
   [179 175 171]
   [177 175 172]
   [172 175 175]]

  [[176 178 171]
   [169 170 179]
   [174 174 174]
   ...
   [172 169 165]
   [159 159 154]
   [153 153 154]]

  [[158 157 154]
   [164 156 152]
   [154 155 159]
   ...
   [174 168 170]
   [169 167 167]
   [170 173 

[[[[135 144 143]
   [144 146 154]
   [124 142 148]
   ...
   [175 175 177]
   [181 175 173]
   [175 179 179]]

  [[177 176 174]
   [172 174 167]
   [170 168 177]
   ...
   [167 168 172]
   [167 162 153]
   [154 158 162]]

  [[161 156 156]
   [159 158 154]
   [154 165 161]
   ...
   [172 169 169]
   [169 169 169]
   [170 173 170]]

  ...

  [[143 142 142]
   [143 141 154]
   [152 147 150]
   ...
   [186 184 185]
   [184 183 179]
   [183 186 185]]

  [[184 186 186]
   [185 185 187]
   [182 181 184]
   ...
   [156 163 164]
   [162 163 164]
   [164 167 169]]

  [[168 170 174]
   [176 177 177]
   [176 175 163]
   ...
   [ 70  73  83]
   [ 77  81  81]
   [164 252 252]]]]
[[[[135 144 143]
   [144 146 154]
   [124 142 148]
   ...
   [175 175 177]
   [181 175 173]
   [175 179 179]]

  [[177 176 174]
   [172 174 167]
   [170 168 177]
   ...
   [167 168 172]
   [167 162 153]
   [154 158 162]]

  [[161 156 156]
   [159 158 154]
   [154 165 161]
   ...
   [172 169 169]
   [169 169 169]
   [170 173 

[[[[140 142 137]
   [128 149 152]
   [132 137 138]
   ...
   [174 174 174]
   [177 177 174]
   [175 177 174]]

  [[173 170 172]
   [172 172 172]
   [173 173 175]
   ...
   [169 169 165]
   [162 161 158]
   [156 157 157]]

  [[157 156 155]
   [154 156 157]
   [157 158 160]
   ...
   [172 173 168]
   [167 168 171]
   [172 172 171]]

  ...

  [[149 141 144]
   [147 148 142]
   [141 144 145]
   ...
   [182 182 181]
   [183 183 182]
   [184 184 186]]

  [[186 183 183]
   [183 183 183]
   [184 187 187]
   ...
   [165 161 162]
   [164 164 163]
   [166 169 167]]

  [[165 170 176]
   [181 184 181]
   [175 176 174]
   ...
   [ 68  68  65]
   [ 81  81  90]
   [167 252 252]]]]
[[[[148 145 143]
   [137 141 147]
   [125 128 130]
   ...
   [176 178 171]
   [177 175 172]
   [175 176 175]]

  [[177 178 179]
   [178 174 172]
   [173 173 174]
   ...
   [167 164 168]
   [162 161 159]
   [154 155 156]]

  [[159 152 157]
   [159 158 155]
   [154 160 159]
   ...
   [168 167 166]
   [164 165 166]
   [170 170 

[[[[146 145 139]
   [137 136 128]
   [136 144 145]
   ...
   [170 175 180]
   [172 172 176]
   [178 172 171]]

  [[177 179 174]
   [173 178 174]
   [175 176 175]
   ...
   [166 165 164]
   [164 165 162]
   [157 154 150]]

  [[155 156 158]
   [158 153 156]
   [157 159 160]
   ...
   [171 169 168]
   [169 169 167]
   [165 170 171]]

  ...

  [[145 148 150]
   [141 147 147]
   [146 147 148]
   ...
   [186 183 182]
   [184 183 183]
   [184 182 181]]

  [[187 186 186]
   [186 187 187]
   [188 183 183]
   ...
   [165 161 161]
   [165 166 165]
   [165 166 166]]

  [[161 165 175]
   [176 177 176]
   [172 175 176]
   ...
   [ 72  74  79]
   [ 84  80  93]
   [138 254 254]]]]
[[[[143 144 137]
   [138 145 137]
   [136 136 141]
   ...
   [175 172 172]
   [174 177 177]
   [177 178 176]]

  [[176 178 174]
   [169 170 178]
   [175 171 174]
   ...
   [172 164 164]
   [162 156 161]
   [162 158 157]]

  [[160 160 159]
   [158 157 156]
   [157 161 158]
   ...
   [170 168 163]
   [164 167 166]
   [166 169 

[[[[145 136 134]
   [137 141 152]
   [131 135 148]
   ...
   [179 176 173]
   [174 176 179]
   [178 174 176]]

  [[178 179 162]
   [174 177 178]
   [172 173 170]
   ...
   [165 164 163]
   [166 158 151]
   [158 158 156]]

  [[156 159 161]
   [159 157 154]
   [158 157 152]
   ...
   [174 170 167]
   [169 170 171]
   [171 170 170]]

  ...

  [[150 149 146]
   [146 140 141]
   [141 142 148]
   ...
   [185 183 181]
   [182 182 187]
   [187 186 182]]

  [[185 186 184]
   [183 184 184]
   [182 184 183]
   ...
   [162 161 162]
   [168 170 166]
   [163 165 167]]

  [[169 167 172]
   [176 180 179]
   [175 170 169]
   ...
   [ 49  73  80]
   [ 83  89  89]
   [173 252 252]]]]
[[[[129 139 123]
   [131 136 137]
   [140 141 142]
   ...
   [178 181 185]
   [179 173 170]
   [178 175 174]]

  [[179 172 178]
   [175 173 174]
   [177 178 177]
   ...
   [168 165 164]
   [160 154 152]
   [153 158 145]]

  [[156 160 155]
   [165 160 160]
   [160 150 165]
   ...
   [170 168 170]
   [163 170 168]
   [174 170 

[[[[145 136 141]
   [146 152 139]
   [134 136 132]
   ...
   [177 185 179]
   [178 181 177]
   [180 167 166]]

  [[179 174 174]
   [175 176 176]
   [176 177 179]
   ...
   [156 163 165]
   [161 159 155]
   [154 157 156]]

  [[156 152 156]
   [156 155 161]
   [161 161 160]
   ...
   [163 171 174]
   [167 168 169]
   [170 167 162]]

  ...

  [[141 143 146]
   [144 145 145]
   [144 146 148]
   ...
   [187 177 181]
   [183 183 186]
   [186 184 184]]

  [[187 183 179]
   [182 184 184]
   [185 184 183]
   ...
   [162 165 164]
   [160 161 164]
   [165 164 165]]

  [[161 160 168]
   [185 176 177]
   [177 172 170]
   ...
   [ 64  76  75]
   [ 73  88  91]
   [166 253 253]]]]
[[[[145 136 141]
   [146 152 139]
   [134 136 132]
   ...
   [177 185 179]
   [178 181 177]
   [180 167 166]]

  [[179 174 174]
   [175 176 176]
   [176 177 179]
   ...
   [156 163 165]
   [161 159 155]
   [154 157 156]]

  [[156 152 156]
   [156 155 161]
   [161 161 160]
   ...
   [163 171 174]
   [167 168 169]
   [170 167 

[[[[146 152 138]
   [141 144 142]
   [136 141 146]
   ...
   [171 178 177]
   [177 177 174]
   [175 170 173]]

  [[177 176 174]
   [175 174 176]
   [178 172 171]
   ...
   [171 167 163]
   [164 167 152]
   [151 163 158]]

  [[158 157 149]
   [157 160 162]
   [157 159 167]
   ...
   [171 171 170]
   [169 170 172]
   [172 173 171]]

  ...

  [[154 147 144]
   [146 148 149]
   [144 146 145]
   ...
   [184 183 181]
   [181 181 179]
   [182 184 184]]

  [[183 184 187]
   [189 187 186]
   [181 180 181]
   ...
   [160 157 160]
   [166 166 167]
   [167 162 169]]

  [[169 173 182]
   [180 179 175]
   [174 174 169]
   ...
   [ 65  69  72]
   [ 73  89  86]
   [137 252 252]]]]
[[[[142 144 150]
   [146 140 133]
   [130 146 150]
   ...
   [180 178 177]
   [177 175 178]
   [179 180 175]]

  [[177 177 177]
   [177 176 179]
   [179 171 173]
   ...
   [168 169 165]
   [164 160 156]
   [156 158 159]]

  [[158 159 162]
   [159 159 161]
   [153 160 166]
   ...
   [170 170 166]
   [169 170 171]
   [171 174 

[[[[146 140 138]
   [136 137 145]
   [145 147 153]
   ...
   [178 175 173]
   [175 177 177]
   [174 170 167]]

  [[174 172 171]
   [170 174 176]
   [174 174 173]
   ...
   [163 170 164]
   [159 155 155]
   [159 159 156]]

  [[158 160 157]
   [158 160 160]
   [162 162 158]
   ...
   [172 174 170]
   [167 170 174]
   [178 170 164]]

  ...

  [[140 146 146]
   [147 143 144]
   [149 147 145]
   ...
   [181 187 183]
   [186 188 189]
   [185 187 188]]

  [[192 189 185]
   [185 184 187]
   [187 186 185]
   ...
   [164 160 161]
   [161 164 165]
   [164 164 165]]

  [[167 171 178]
   [182 179 174]
   [173 174 176]
   ...
   [ 65  65  72]
   [ 65  75  89]
   [152 251 252]]]]
[[[[146 140 138]
   [136 137 145]
   [145 147 153]
   ...
   [178 175 173]
   [175 177 177]
   [174 170 167]]

  [[174 172 171]
   [170 174 176]
   [174 174 173]
   ...
   [163 170 164]
   [159 155 155]
   [159 159 156]]

  [[158 160 157]
   [158 160 160]
   [162 162 158]
   ...
   [172 174 170]
   [167 170 174]
   [178 170 

[[[[134 139 139]
   [135 135 131]
   [134 138 136]
   ...
   [175 174 174]
   [173 177 177]
   [176 176 175]]

  [[177 171 171]
   [176 175 175]
   [170 172 177]
   ...
   [170 166 171]
   [163 155 157]
   [160 168 163]]

  [[158 157 159]
   [162 161 158]
   [157 157 159]
   ...
   [175 171 169]
   [168 169 170]
   [170 171 168]]

  ...

  [[144 139 141]
   [143 144 142]
   [141 142 148]
   ...
   [184 185 183]
   [183 184 184]
   [183 182 185]]

  [[186 183 183]
   [184 187 186]
   [184 184 183]
   ...
   [160 163 163]
   [163 164 166]
   [164 162 164]]

  [[167 169 171]
   [178 185 178]
   [179 175 171]
   ...
   [ 76  79  72]
   [ 71  74  88]
   [162 251 251]]]]
[[[[134 139 139]
   [135 135 131]
   [134 138 136]
   ...
   [175 174 174]
   [173 177 177]
   [176 176 175]]

  [[177 171 171]
   [176 175 175]
   [170 172 177]
   ...
   [170 166 171]
   [163 155 157]
   [160 168 163]]

  [[158 157 159]
   [162 161 158]
   [157 157 159]
   ...
   [175 171 169]
   [168 169 170]
   [170 171 

[[[[144 143 142]
   [142 142 145]
   [134 136 144]
   ...
   [175 175 168]
   [167 170 174]
   [177 166 162]]

  [[169 170 172]
   [174 170 182]
   [172 170 177]
   ...
   [162 161 159]
   [162 153 152]
   [153 157 162]]

  [[155 156 159]
   [159 160 160]
   [162 165 156]
   ...
   [170 170 170]
   [170 170 168]
   [169 168 168]]

  ...

  [[148 148 142]
   [148 146 146]
   [149 149 147]
   ...
   [184 184 184]
   [184 181 184]
   [184 184 184]]

  [[186 186 184]
   [184 187 187]
   [185 184 186]
   ...
   [164 165 165]
   [164 161 165]
   [165 167 164]]

  [[165 171 173]
   [176 178 180]
   [178 175 172]
   ...
   [ 66  65  72]
   [ 86  85  88]
   [172 252 252]]]]
[[[[144 143 142]
   [142 142 145]
   [134 136 144]
   ...
   [175 175 168]
   [167 170 174]
   [177 166 162]]

  [[169 170 172]
   [174 170 182]
   [172 170 177]
   ...
   [162 161 159]
   [162 153 152]
   [153 157 162]]

  [[155 156 159]
   [159 160 160]
   [162 165 156]
   ...
   [170 170 170]
   [170 170 168]
   [169 168 

[[[[138 138 133]
   [129 133 140]
   [139 139 140]
   ...
   [170 177 178]
   [175 169 171]
   [172 175 174]]

  [[174 174 174]
   [176 174 174]
   [174 174 174]
   ...
   [166 164 163]
   [162 156 153]
   [155 154 155]]

  [[156 158 151]
   [152 159 159]
   [161 162 160]
   ...
   [169 171 171]
   [169 165 162]
   [163 176 170]]

  ...

  [[134 135 145]
   [145 149 153]
   [146 141 145]
   ...
   [182 183 181]
   [183 183 185]
   [187 186 184]]

  [[187 187 185]
   [184 186 188]
   [188 187 184]
   ...
   [162 169 168]
   [168 169 163]
   [162 164 167]]

  [[167 167 178]
   [181 177 175]
   [172 176 170]
   ...
   [ 68  70  66]
   [ 80  88  86]
   [172 252 252]]]]
[[[[140 150 140]
   [137 138 134]
   [139 130 144]
   ...
   [172 177 176]
   [179 176 170]
   [175 171 175]]

  [[178 175 163]
   [172 173 173]
   [174 178 176]
   ...
   [164 166 160]
   [155 154 161]
   [158 157 154]]

  [[153 156 160]
   [160 159 160]
   [159 159 154]
   ...
   [170 171 173]
   [170 167 166]
   [163 171 

[[[[154 139 145]
   [145 146 154]
   [139 139 144]
   ...
   [163 177 179]
   [179 178 175]
   [175 177 174]]

  [[175 175 172]
   [173 174 156]
   [172 172 176]
   ...
   [169 166 164]
   [165 161 160]
   [162 155 154]]

  [[157 162 162]
   [158 156 158]
   [151 158 161]
   ...
   [171 167 167]
   [168 171 170]
   [169 168 170]]

  ...

  [[144 145 145]
   [145 145 147]
   [147 145 144]
   ...
   [184 184 185]
   [186 186 185]
   [184 182 179]]

  [[186 191 186]
   [185 186 186]
   [184 185 186]
   ...
   [162 162 168]
   [172 166 166]
   [167 163 169]]

  [[169 170 173]
   [176 181 180]
   [181 178 175]
   ...
   [ 63  67  77]
   [ 80  85  91]
   [170 253 253]]]]
[[[[154 139 145]
   [145 146 154]
   [139 139 144]
   ...
   [163 177 179]
   [179 178 175]
   [175 177 174]]

  [[175 175 172]
   [173 174 156]
   [172 172 176]
   ...
   [169 166 164]
   [165 161 160]
   [162 155 154]]

  [[157 162 162]
   [158 156 158]
   [151 158 161]
   ...
   [171 167 167]
   [168 171 170]
   [169 168 

[[[[140 149 144]
   [140 139 139]
   [137 151 146]
   ...
   [176 173 174]
   [171 172 178]
   [169 170 171]]

  [[174 176 171]
   [169 174 179]
   [171 169 173]
   ...
   [168 166 170]
   [163 158 160]
   [160 161 162]]

  [[162 158 155]
   [156 156 159]
   [155 152 151]
   ...
   [165 164 169]
   [170 171 170]
   [168 169 171]]

  ...

  [[140 145 138]
   [146 148 145]
   [145 147 148]
   ...
   [182 178 180]
   [182 183 184]
   [183 183 184]]

  [[186 186 183]
   [183 185 185]
   [183 184 187]
   ...
   [162 162 162]
   [166 168 167]
   [166 168 167]]

  [[165 171 176]
   [177 178 174]
   [172 172 173]
   ...
   [ 60  61  73]
   [ 90  97  86]
   [166 253 253]]]]
[[[[140 149 144]
   [140 139 139]
   [137 151 146]
   ...
   [176 173 174]
   [171 172 178]
   [169 170 171]]

  [[174 176 171]
   [169 174 179]
   [171 169 173]
   ...
   [168 166 170]
   [163 158 160]
   [160 161 162]]

  [[162 158 155]
   [156 156 159]
   [155 152 151]
   ...
   [165 164 169]
   [170 171 170]
   [168 169 

[[[[142 147 142]
   [135 144 146]
   [137 122 137]
   ...
   [178 172 170]
   [171 174 179]
   [184 174 173]]

  [[178 180 178]
   [174 172 172]
   [173 173 173]
   ...
   [165 167 165]
   [164 160 157]
   [157 158 158]]

  [[155 155 157]
   [158 157 157]
   [159 163 164]
   ...
   [171 169 169]
   [168 171 173]
   [170 170 170]]

  ...

  [[154 153 147]
   [150 147 150]
   [147 144 144]
   ...
   [182 185 184]
   [182 184 184]
   [184 183 184]]

  [[183 179 188]
   [189 185 184]
   [186 186 179]
   ...
   [164 165 166]
   [161 157 164]
   [168 168 169]]

  [[173 167 178]
   [182 181 178]
   [175 175 175]
   ...
   [ 50  52  59]
   [ 73  81  81]
   [166 252 252]]]]
[[[[134 128 140]
   [146 146 138]
   [134 136 136]
   ...
   [176 179 175]
   [174 180 178]
   [173 170 175]]

  [[174 174 177]
   [179 173 171]
   [172 167 172]
   ...
   [170 172 170]
   [158 162 161]
   [157 157 154]]

  [[156 162 156]
   [155 159 159]
   [158 157 159]
   ...
   [171 167 169]
   [170 167 171]
   [173 176 

[[[[128 131 139]
   [141 142 145]
   [146 144 143]
   ...
   [181 179 173]
   [179 166 170]
   [180 174 173]]

  [[174 175 176]
   [176 178 177]
   [174 173 175]
   ...
   [165 165 166]
   [165 160 156]
   [156 155 155]]

  [[158 161 161]
   [162 157 156]
   [158 162 161]
   ...
   [172 170 166]
   [168 170 171]
   [174 167 166]]

  ...

  [[148 146 146]
   [152 149 147]
   [149 149 147]
   ...
   [181 186 183]
   [178 180 184]
   [183 180 183]]

  [[185 184 185]
   [187 187 187]
   [188 185 183]
   ...
   [165 167 165]
   [162 170 169]
   [169 170 169]]

  [[166 168 172]
   [174 174 173]
   [171 173 168]
   ...
   [ 71  78  75]
   [ 88 100  89]
   [164 251 251]]]]
[[[[128 131 139]
   [141 142 145]
   [146 144 143]
   ...
   [181 179 173]
   [179 166 170]
   [180 174 173]]

  [[174 175 176]
   [176 178 177]
   [174 173 175]
   ...
   [165 165 166]
   [165 160 156]
   [156 155 155]]

  [[158 161 161]
   [162 157 156]
   [158 162 161]
   ...
   [172 170 166]
   [168 170 171]
   [174 167 

[[[[143 138 131]
   [135 145 129]
   [133 140 144]
   ...
   [168 170 171]
   [174 175 176]
   [177 182 176]]

  [[169 171 178]
   [177 170 172]
   [174 170 169]
   ...
   [169 168 167]
   [160 158 158]
   [158 160 161]]

  [[157 154 153]
   [152 153 155]
   [154 153 150]
   ...
   [165 171 170]
   [169 164 160]
   [162 170 171]]

  ...

  [[146 144 143]
   [144 144 145]
   [145 145 145]
   ...
   [184 183 184]
   [186 185 184]
   [182 182 182]]

  [[185 188 185]
   [184 187 184]
   [183 186 186]
   ...
   [164 165 162]
   [165 168 165]
   [163 162 162]]

  [[169 170 174]
   [178 186 178]
   [175 175 177]
   ...
   [ 65  59  69]
   [ 93  93  87]
   [159 252 252]]]]
[[[[143 138 131]
   [135 145 129]
   [133 140 144]
   ...
   [168 170 171]
   [174 175 176]
   [177 182 176]]

  [[169 171 178]
   [177 170 172]
   [174 170 169]
   ...
   [169 168 167]
   [160 158 158]
   [158 160 161]]

  [[157 154 153]
   [152 153 155]
   [154 153 150]
   ...
   [165 171 170]
   [169 164 160]
   [162 170 

[[[[137 140 139]
   [142 150 146]
   [141 147 139]
   ...
   [170 180 179]
   [173 173 171]
   [172 174 170]]

  [[170 171 174]
   [171 169 176]
   [170 169 175]
   ...
   [170 177 168]
   [165 161 157]
   [155 154 156]]

  [[152 160 159]
   [159 159 159]
   [159 158 159]
   ...
   [172 169 169]
   [171 171 168]
   [167 171 167]]

  ...

  [[145 139 138]
   [145 147 141]
   [140 145 144]
   ...
   [182 183 183]
   [183 180 177]
   [180 183 183]]

  [[182 185 187]
   [188 189 185]
   [186 185 184]
   ...
   [162 162 161]
   [162 164 168]
   [169 170 169]]

  [[161 172 181]
   [177 176 177]
   [177 177 178]
   ...
   [ 65  65  63]
   [ 74  89  96]
   [169 251 251]]]]
[[[[154 140 139]
   [141 133 145]
   [149 141 138]
   ...
   [174 176 170]
   [170 174 176]
   [179 174 171]]

  [[176 177 175]
   [173 169 173]
   [175 172 173]
   ...
   [168 170 170]
   [163 157 155]
   [157 150 156]]

  [[155 162 162]
   [157 156 158]
   [157 149 153]
   ...
   [169 168 167]
   [170 170 171]
   [169 166 

[[[[145 146 146]
   [139 148 149]
   [145 141 142]
   ...
   [176 172 172]
   [177 176 174]
   [174 173 172]]

  [[171 174 173]
   [173 174 174]
   [174 173 174]
   ...
   [167 166 161]
   [160 154 155]
   [159 158 158]]

  [[159 159 158]
   [158 153 152]
   [152 158 155]
   ...
   [170 169 169]
   [169 171 174]
   [173 169 170]]

  ...

  [[153 149 146]
   [151 150 148]
   [145 143 147]
   ...
   [179 183 187]
   [181 181 183]
   [187 189 190]]

  [[184 184 184]
   [184 184 184]
   [183 184 184]
   ...
   [163 163 162]
   [163 164 163]
   [165 165 168]]

  [[167 170 172]
   [177 177 177]
   [175 178 177]
   ...
   [ 66  62  70]
   [ 70  75  82]
   [137 252 254]]]]
[[[[145 145 144]
   [144 148 146]
   [135 138 136]
   ...
   [177 180 171]
   [174 179 176]
   [179 174 172]]

  [[174 173 174]
   [170 166 172]
   [175 170 171]
   ...
   [169 167 162]
   [163 164 157]
   [152 152 153]]

  [[157 158 158]
   [156 157 158]
   [160 158 161]
   ...
   [167 186 172]
   [165 170 173]
   [172 170 

[[[[144 143 142]
   [144 147 153]
   [150 149 137]
   ...
   [172 168 170]
   [174 174 167]
   [174 170 169]]

  [[182 184 175]
   [176 177 172]
   [171 174 176]
   ...
   [169 171 166]
   [165 165 163]
   [160 158 157]]

  [[157 162 162]
   [160 155 158]
   [164 162 159]
   ...
   [173 177 171]
   [169 166 165]
   [170 172 170]]

  ...

  [[145 146 147]
   [151 149 147]
   [144 142 142]
   ...
   [185 180 183]
   [184 182 182]
   [185 185 184]]

  [[183 183 187]
   [179 186 187]
   [186 186 187]
   ...
   [162 164 165]
   [166 165 165]
   [167 167 169]]

  [[170 172 178]
   [178 179 183]
   [181 177 173]
   ...
   [ 65  72  75]
   [ 81  80  90]
   [163 252 252]]]]
[[[[144 143 142]
   [144 147 153]
   [150 149 137]
   ...
   [172 168 170]
   [174 174 167]
   [174 170 169]]

  [[182 184 175]
   [176 177 172]
   [171 174 176]
   ...
   [169 171 166]
   [165 165 163]
   [160 158 157]]

  [[157 162 162]
   [160 155 158]
   [164 162 159]
   ...
   [173 177 171]
   [169 166 165]
   [170 172 

[[[[138 142 145]
   [143 142 145]
   [146 145 142]
   ...
   [177 176 174]
   [174 176 174]
   [174 174 174]]

  [[172 170 172]
   [175 178 177]
   [177 175 175]
   ...
   [168 162 164]
   [167 163 153]
   [158 161 162]]

  [[162 160 158]
   [159 162 158]
   [158 162 157]
   ...
   [171 166 164]
   [171 171 167]
   [169 168 168]]

  ...

  [[149 145 146]
   [148 147 144]
   [144 147 146]
   ...
   [190 181 177]
   [180 177 178]
   [184 182 182]]

  [[182 184 185]
   [185 185 183]
   [183 183 184]
   ...
   [165 164 162]
   [165 173 178]
   [171 169 168]]

  [[165 162 173]
   [168 170 178]
   [177 172 170]
   ...
   [ 69  69  65]
   [ 72  79  89]
   [130 251 252]]]]
[[[[132 140 140]
   [139 134 146]
   [145 135 138]
   ...
   [175 174 177]
   [175 173 174]
   [177 174 172]]

  [[170 169 174]
   [177 178 178]
   [182 170 176]
   ...
   [167 169 170]
   [161 156 156]
   [155 153 153]]

  [[161 154 154]
   [155 158 159]
   [160 160 158]
   ...
   [171 175 172]
   [171 171 171]
   [171 170 

[[[[148 146 137]
   [144 151 141]
   [140 137 137]
   ...
   [170 173 177]
   [175 175 176]
   [175 176 176]]

  [[170 174 177]
   [177 177 180]
   [176 173 176]
   ...
   [167 175 175]
   [169 161 153]
   [154 156 155]]

  [[153 156 160]
   [160 160 161]
   [158 152 159]
   ...
   [173 170 170]
   [170 169 169]
   [173 177 169]]

  ...

  [[139 140 143]
   [141 145 142]
   [137 146 147]
   ...
   [185 187 185]
   [182 181 181]
   [182 184 184]]

  [[184 186 188]
   [186 186 186]
   [187 187 185]
   ...
   [158 160 160]
   [163 161 164]
   [175 170 165]]

  [[165 170 174]
   [177 176 175]
   [177 177 169]
   ...
   [ 65  70  72]
   [ 75  81  85]
   [174 252 252]]]]
[[[[148 146 137]
   [144 151 141]
   [140 137 137]
   ...
   [170 173 177]
   [175 175 176]
   [175 176 176]]

  [[170 174 177]
   [177 177 180]
   [176 173 176]
   ...
   [167 175 175]
   [169 161 153]
   [154 156 155]]

  [[153 156 160]
   [160 160 161]
   [158 152 159]
   ...
   [173 170 170]
   [170 169 169]
   [173 177 